### ISSUE TITLE
Error in cbioportal-container when spinning up backend instance

### ISSUE THREAD

**Issue by gblaih** [cBioPortal/cbioportal#10698]
Getting this error in docker `cbioportal-container` logs when spinning up backend instance for localdb e2e testing. Other machines don't appear to be getting this issue; may be only affecting intel chip machines?

`ERROR 150 --- [nio-8080-exec-5] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed: java.lang.NoSuchMethodError: org.bson.json.JsonWriterSettings: method 'void <init>()' not found] with root cause
java.lang.NoSuchMethodError: org.bson.json.JsonWriterSettings: method 'void <init>()' not found`

**Comment by sellth** [comment]
Also running into this error after updating our instance to v6. Any idea about the cause?
```
ERROR 74 --- [nio-8080-exec-5] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed: java.lang.NoSuchMethodError: org.bson.json.JsonWriterSettings: method 'void <init>()' not found] with root cause

java.lang.NoSuchMethodError: org.bson.json.JsonWriterSettings: method 'void <init>()' not found
	at com.mongodb.BasicDBObject.toJson(BasicDBObject.java:154) ~[mongo-java-driver-3.12.14.jar:na]
	at com.mongodb.BasicDBObject.toString(BasicDBObject.java:238) ~[mongo-java-driver-3.12.14.jar:na]
	at org.cbioportal.web.SessionServiceController.getUserStudies(SessionServiceController.java:238) ~[cbioportal-webapp/:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
...
```

**Comment by haynescd** [comment]
@sellth Can you try and see if the issue is resolved on your end as well (after the PR)

**Comment by sellth** [comment]
@haynescd This solved it, thanks!
